{{- if .Values.environmentVars.configMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.envResourceName" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
  {{- with .Values.environmentVars.configMap }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}