{{- if .Values.environmentVars.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.envResourceName" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  {{- with .Values.environmentVars.secret }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
